### model
model_name_or_path: /home/original_models/DeepSeek-R1-0528-Qwen3-8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: claude_4_0514_passed_allthink_hf_format
template: deepseekr1
cutoff_len: 20480
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /shared_workspace_mfs/alex/llama-factory-chkpts/qwen3-8b_7k_deepseek_2/full/qwen3_8b_deepseek_distill_claude_sft_allthink_hf_format
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: qwen3_8b_deepseek_distill_claude_sft_allthink_hf_format

### train
flash_attn: fa2
enable_liger_kernel: true
use_unsloth_gc: true
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
